version: "3.8"
services:
  backend:
    image: webbylabhub/movies
    ports:
      - "8000:8000"

  frontend:
    image: marusya1/movies-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
